/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  collections: {
    pages: Page;
    media: Media;
    users: User;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    header: Header;
    footer: Footer;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface Page {
  id: number;
  title: string;
  slug?: string | null;
  layout?:
    | (
        | HeroBlock
        | FeaturesBlock
        | CTABlock
        | TestimonialsBlock
        | PricingBlock
        | FAQBlock
        | ContentBlock
        | MediaBlock
        | StatsBlock
        | FormBlock
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (number | null) | Media;
  };
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
export interface HeroBlock {
  heading: string;
  subheading?: string | null;
  media?: (number | null) | Media;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('primary' | 'secondary' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  variant?: ('default' | 'centered' | 'split') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'hero';
}
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
export interface FeaturesBlock {
  heading?: string | null;
  description?: string | null;
  features?:
    | {
        icon?: string | null;
        title: string;
        description: string;
        id?: string | null;
      }[]
    | null;
  columns?: ('two' | 'three' | 'four') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'features';
}
export interface CTABlock {
  heading: string;
  description?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('primary' | 'secondary' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  variant?: ('default' | 'centered' | 'banner') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
export interface TestimonialsBlock {
  heading?: string | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        role?: string | null;
        company?: string | null;
        avatar?: (number | null) | Media;
        rating?: number | null;
        id?: string | null;
      }[]
    | null;
  variant?: ('grid' | 'carousel' | 'single') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
export interface PricingBlock {
  heading?: string | null;
  description?: string | null;
  tiers?:
    | {
        name: string;
        price: string;
        period?: string | null;
        description?: string | null;
        features?: string | null;
        highlighted?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
          appearance?: ('primary' | 'secondary' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'pricing';
}
export interface FAQBlock {
  heading?: string | null;
  questions?:
    | {
        question: string;
        answer: string;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'faq';
}
export interface ContentBlock {
  content: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  maxWidth?: ('sm' | 'md' | 'lg' | 'xl' | 'full') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
export interface MediaBlock {
  media: number | Media;
  caption?: string | null;
  aspectRatio?: ('auto' | 'square' | 'video' | 'wide') | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'media';
}
export interface StatsBlock {
  heading?: string | null;
  stats?:
    | {
        value: string;
        label: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'stats';
}
export interface FormBlock {
  heading?: string | null;
  description?: string | null;
  fields?:
    | {
        fieldType: 'text' | 'email' | 'textarea' | 'select';
        label: string;
        name: string;
        required?: boolean | null;
        placeholder?: string | null;
        options?: string | null;
        id?: string | null;
      }[]
    | null;
  submitButtonLabel?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'form';
}
export interface User {
  id: number;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
export interface Header {
  id: number;
  logo?: (number | null) | Media;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?: {
            relationTo: 'pages';
            value: number | Page;
          } | null;
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface Footer {
  id: number;
  logo?: (number | null) | Media;
  columns?:
    | {
        heading?: string | null;
        links?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                newTab?: boolean | null;
                reference?: {
                  relationTo: 'pages';
                  value: number | Page;
                } | null;
                url?: string | null;
                label: string;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  layout?:
    | T
    | {
        hero?: T | HeroBlockSelect<T>;
        features?: T | FeaturesBlockSelect<T>;
        cta?: T | CTABlockSelect<T>;
        testimonials?: T | TestimonialsBlockSelect<T>;
        pricing?: T | PricingBlockSelect<T>;
        faq?: T | FAQBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        media?: T | MediaBlockSelect<T>;
        stats?: T | StatsBlockSelect<T>;
        form?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
export interface HeroBlockSelect<T extends boolean = true> {
  heading?: T;
  subheading?: T;
  media?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  variant?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
export interface FeaturesBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  features?:
    | T
    | {
        icon?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  columns?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface CTABlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  variant?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface TestimonialsBlockSelect<T extends boolean = true> {
  heading?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        company?: T;
        avatar?: T;
        rating?: T;
        id?: T;
      };
  variant?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface PricingBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  tiers?:
    | T
    | {
        name?: T;
        price?: T;
        period?: T;
        description?: T;
        features?: T;
        highlighted?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface FAQBlockSelect<T extends boolean = true> {
  heading?: T;
  questions?:
    | T
    | {
        question?: T;
        answer?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface ContentBlockSelect<T extends boolean = true> {
  content?: T;
  maxWidth?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  caption?: T;
  aspectRatio?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface StatsBlockSelect<T extends boolean = true> {
  heading?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface FormBlockSelect<T extends boolean = true> {
  heading?: T;
  description?: T;
  fields?:
    | T
    | {
        fieldType?: T;
        label?: T;
        name?: T;
        required?: T;
        placeholder?: T;
        options?: T;
        id?: T;
      };
  submitButtonLabel?: T;
  id?: T;
  blockName?: T;
  blockType?: T;
}
export interface UsersSelect<T extends boolean = true> {
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
export interface FooterSelect<T extends boolean = true> {
  logo?: T;
  columns?:
    | T
    | {
        heading?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
}



